version: "3.3"

services:
  mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped
