version: "2.1"

services:
  dm-manager:
    image: harbor.cs.dm.unipi.it/dm-manager/dm-manager
    entrypoint: ["./entrypoint.sh", "server"]
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    environment:
      MONGO_URI: "mongodb://mongodb:27017/dm-manager"
      STATIC_FILES_PATH: "build"
      # ADMIN_USER: "admin"
      # ADMIN_PASSWORD: "secret"
      # SESSION_SECRET: "1234567890"
      # JWT_SECRET: "1234567890"
      # CORS_ORIGIN: "http://localhost:3000"
      # PORT: "8000"
      OAUTH2_AUTHORIZE_URL: "https://iam.unipi.it/oauth2/authorize"
      OAUTH2_TOKEN_URL: "https://iam.unipi.it/oauth2/token"
      OAUTH2_USERINFO_URL: "https://iam.unipi.it/oauth2/userinfo"
      OAUTH2_LOGOUT_URL: "https://iam.unipi.it/oidc/logout"
      # OAUTH2_CLIENT_ID: 1234567890
      # OAUTH2_CLIENT_SECRET: "1234567890"
      # OAUTH2_USERNAME_FIELD: "email"
      # REACT_APP_SERVER_URL: ""
    ports:
      - 8000:8000
    networks:
      - backend

  worker:
    image: harbor.cs.dm.unipi.it/dm-manager/dm-manager
    entrypoint: ["./entrypoint.sh", "worker"]
    restart: unless-stopped
    environment:
      MONGO_URI: "mongodb://mongodb:27017/dm-manager"
    networks:
      - backend

  mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
#    ports:
#      - 27017:27017
    networks:
      - backend
    restart: unless-stopped

networks:
  backend: