version: "3.3"

services:
  mongodb:
    image: mongo:6
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped

#  nginx:
#    image: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "8080:80"
