version: "3.3"

# This docker-compose configuration file is used to run 
# all the external services which are required for the 
# application to run locally.
#
# At the moment, the only external service is MongoDB.
#
# If you want to run the entire application in docker,
# look instead at the configuration file
#
#  docker-compose-production.yml
#
# which will run both the application and the external services
# in docker containers.

services:
  mongodb:
    image: mongo:6
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped

  worker:
    image: robol/dm-worker
    environment:
      MONGO_URI: "mongodb://mongodb:27017/dm-manager"

#  nginx:
#    image: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "8080:80"
