module.exports = [
{
    "name": "Analisi di reti complesse: dalla teoria alle applicazioni",
    "identifier": "PRA_2020_61",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2020 - 2021",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "",
    "localCoordinator": "Federico Giovanni  Poloni",
    "members": "Leonardo Robol,  Beatrice Meini,  Paola Boito ",
    "startDate": "2020-07-07",
    "endDate": "2022-12-31",
    "webSite": ""
  },
     {
    "name": "Neurons, Odorants, Maths, Sleep: get insight into the molecular mechanisms of cognitive impairment",
    "identifier": "PRA_2020_31",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2020 - 2021",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "",
    "localCoordinator": "Anna Baccaglini-Frank",
    "members": "Enrica Bonanni, Alessandra Braca, Eleonora Da Pozzo, Marinella De Leo, Pietro Di Martino, Guido Flamini, Ferdinando Franzoni, Lorenzo Germelli, Chiara Giacomelli, Claudia Martini, Luisa Pistelli, Maria Letizia Trincavelli",
    "startDate": "2020-07-07",
    "endDate": "2022-12-31",
    "webSite": ""
  },
     {
    "name": "Nuovi sviluppi per minimi dell'energia in problemi di ottimizzazione di forma",
    "identifier": "PRA_2020_65",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2020 - 2021",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "",
    "localCoordinator": "Aldo Pratelli",
    "members": "Giovanni Alberti, Konstantinos Bessas, Giuseppe Buttazzo, Maria Stella Gelli, Matteo Novaga, Alessandra Pluda, Vincenzo Scattaglia",
    "startDate": "2020-07-07",
    "endDate": "2022-12-31",
    "webSite": ""
  },
     {
    "name": "Spazi di moduli, geometria aritmetica e aspetti storici",
    "identifier": "PRA_2020_40",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2020 - 2021",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "",
    "localCoordinator": "Mattia Talpo",
    "members": "Andrea Bandini, Alberto Cogliati, Valerio Melani, Francesco Sala, Tamás Szamuely",
    "startDate": "2020-07-07",
    "endDate": "2022-12-31",
    "webSite": ""
  },
     {
    "name": "Sistemi dinamici in logica, geometria, fisica matematica e scienza delle costruzioni",
    "identifier": "PRA_2020_82",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2020 - 2021",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "",
    "localCoordinator": "Giacomo Tommei",
    "members": "Marco Abate, Riccardo Barsotti, Giulio Baù, Alessandro Berarducci, Gianluigi Del Magno, Mauro Di Nasso, Giovanni Federico Gronchi, Stefano Marò, Giacomo Lari, Daniele Serra, David-Antonio-Riccardo Mustaro",
    "startDate": "2020-07-07",
    "endDate": "2022-12-31",
    "webSite": ""
  },
     {
    "name": "Spazi di moduli, rappresentazioni e strutture combinatorie",
    "identifier": "PRA_2018_5",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2018 - 2019",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "",
    "localCoordinator": "Rita Pardini",
    "members": "Ilaria Del Corso, Marco Franciosi, Giovanni Gaiffi, Andrea Maffei, Enrico Sbarra",
    "startDate": "2018-08-09",
    "endDate": "2020-12-31",
    "webSite": ""
  },
     {
    "name": "Sistemi dinamici in analisi, geometria, logica e meccanica celeste",
    "identifier": "PRA_2017_22",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2017 - 2018",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "",
    "localCoordinator": "Marco Abate",
    "members": "Marco Abate, Claudio Bonanno, Mauro Di Nasso, Stefano Galatolo, Alessandro Berarducci, Giovanni Federico Gronchi, Carlo Carminati, Giacomo Tommei",
    "startDate": "2017-04-10",
    "endDate": "2019-04-09",
    "webSite": ""
  },
     {
    "name": "Problemi di ottimizzazione e di evoluzione in ambito variazionale",
    "identifier": "PRA_2017_23",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2017 - 2018",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "",
    "localCoordinator": "Matteo Novaga",
    "members": "",
    "startDate": "2017-04-10",
    "endDate": "2019-04-09",
    "webSite": ""
  },
     {
    "name": "PROmoting STEAM in primary school: partnership for disseminating good practices – ProSTEAM",
    "identifier": "Project Number 2021-1-PT01-KA220-SCH-000027742",
    "projectType": "Erasmus+  Strategic Partnerships Key Action 2 Cooperation partnerships in school education",
    "funds": "Internazionale",
    "fundingEntity": "Europeo",
    "pi": "",
    "localCoordinator": "Anna Baccaglini-Frank",
    "members": "Alessandro Ramploud, Silvia Funghi, Maria Alessandra Mariotti",
    "startDate": null,
    "endDate": null,
    "webSite": ""
  },
     {
    "name": "ITN Stardust - Workpackage Close-Range Navigation and Manipulation of Space Debris and Asteroids",
    "identifier": "Grant Agreement Number 317185",
    "projectType": "FP7 Marie Curie Initial Training Networks (ITN) scheme",
    "funds": "Internazionale",
    "fundingEntity": "Europeo",
    "pi": "",
    "localCoordinator": "Giovanni Federico Gronchi",
    "members": "Helene Ma, Stefano Marò",
    "startDate": "2013-02-01",
    "endDate": "2017-01-31",
    "webSite": "https://robotik.dfki-bremen.de/en/research/projects/itn-stardust.html"
  },
     {
    "name": "Variational approach to the regularity of the free boundaries",
    "identifier": "ERC-2019-STG-VAREG",
    "projectType": "H2020-EU.1.1. - Excellent Science - European Research Council (ERC)",
    "funds": "Internazionale",
    "fundingEntity": "Europeo",
    "pi": "Bozhidar Velichkov",
    "localCoordinator": "",
    "members": "",
    "startDate": "2020-06-01",
    "endDate": "2025-05-31",
    "webSite": "http://www.velichkov.it/vareg.html"
  },
     {
    "name": "Stardust - Reloaded",
    "identifier": "STARDUST-R H2020-MSCA-ITN-2018",
    "projectType": "H2020-EU.1.3.1. - Excellent Science - Marie Skłodowska-Curie Actions",
    "funds": "Internazionale",
    "fundingEntity": "Europeo",
    "pi": "",
    "localCoordinator": "Giovanni Federico Gronchi",
    "members": "G. Baù, I. Cavallari, O. Rodriguez",
    "startDate": "2018-11-21",
    "endDate": "2022-12-31",
    "webSite": "https://cordis.europa.eu/project/id/813644"
  },
     {
    "name": "PerContare",
    "identifier": "",
    "projectType": "Progetto di Fondazione ASPHI Onlus per la scuola primaria",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "",
    "localCoordinator": "Anna Baccaglini-Frank",
    "members": "Alessandro Ramploud, Silvia Funghi",
    "startDate": null,
    "endDate": null,
    "webSite": "https://www.percontare.it/"
  },
     {
    "name": "Didattica della Matematica Inclusiva",
    "identifier": "",
    "projectType": "IPRASE",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "",
    "localCoordinator": "Anna Baccaglini-Frank",
    "members": "Giulia Lisarelli, Federica Poli",
    "startDate": null,
    "endDate": null,
    "webSite": "https://www.iprase.tn.it/matematica-inclusiva-21"
  },
     {
    "name": "DIGiMath",
    "identifier": "",
    "projectType": "Progetto nazionale per la scuola secondaria di secondo grado",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Giovannina Albano (Università del Salento)",
    "localCoordinator": "",
    "members": "Anna Baccaglini-Frank",
    "startDate": null,
    "endDate": null,
    "webSite": "https://sites.google.com/unisa.it/digimath/home-page?authuser=0"
  },
     {
    "name": "Radioscienza per BepiColombo e Juno: prosecuzione attività scientifiche",
    "identifier": "",
    "projectType": "ASI Addendum Contract",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Luciano Iess (Università di Roma La Sapienza)",
    "localCoordinator": "Giacomo Tommei",
    "members": "Giacomo Lari, Orlando Luongo, Giulia Schettino, Daniele Serra",
    "startDate": "2020-04-21",
    "endDate": "2022-04-20",
    "webSite": ""
  },
     {
    "name": "Radioscienza per BepiColombo e Juno: prosecuzione attività scientifiche",
    "identifier": "",
    "projectType": "ASI Contract",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Luciano Iess (Università di Roma La Sapienza)",
    "localCoordinator": "Giacomo Tommei",
    "members": "Giacomo Lari, Giulia Schettino, Daniele Serra",
    "startDate": "2017-12-21",
    "endDate": "2020-03-20",
    "webSite": ""
  },
     {
    "name": "Radioscienza per BepiColombo e Juno - fasi B2/C/D - Attività scientifiche",
    "identifier": "",
    "projectType": "ASI Contract",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Luciano Iess (Università di Roma La Sapienza)",
    "localCoordinator": "Andrea Milani",
    "members": "Giacomo Tommei",
    "startDate": "2009-12-23",
    "endDate": "2017-07-20",
    "webSite": ""
  },
     {
    "name": "Radioscienza per BepiColombo e Juno - fasi B2/C/D - Attività scientifiche",
    "identifier": "",
    "projectType": "ASI Contract",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Luciano Iess (Università di Roma La Sapienza)",
    "localCoordinator": "Andrea Milani",
    "members": "Giacomo Tommei",
    "startDate": "2007-01-12",
    "endDate": "2009-01-11",
    "webSite": ""
  },
     {
    "name": "Project Metodi low-rank per problemi di algebra lineare con struttura data-sparse",
    "identifier": "",
    "projectType": "INdAM/GNCS Project",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "",
    "localCoordinator": "Leonardo Robol",
    "members": "Dario A. Bini, Beatrice Meini, Fabio Durastante, Paola Boito",
    "startDate": "2021-01-01",
    "endDate": "2021-12-31",
    "webSite": ""
  },
     {
    "name": "Attività scientifiche per la Missione Hera",
    "identifier": "",
    "projectType": "Missione HERA - ASI-  Università di Bologna",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Paolo Tortora (Università di Bologna)",
    "localCoordinator": "Giacomo Tommei",
    "members": "Giacomo Lari",
    "startDate": "2022-04-06",
    "endDate": "2025-04-05",
    "webSite": ""
  },
     {
    "name": "Variational methods for stationary and evolution problems with singularities and interfaces",
    "identifier": "",
    "projectType": "Prin 2017",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Gianni Dal Maso (SISSA, Trieste)",
    "localCoordinator": "Giovanni Alberti",
    "members": "Lucia De Luca, Maria Stella Gelli, Matteo Novaga",
    "startDate": "2019-08-01",
    "endDate": "2023-02-19",
    "webSite": ""
  },
     {
    "name": "New frontiers of Celestial Mechanics: theory and applications",
    "identifier": "",
    "projectType": "Prin 2017",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Alessandra Celetti (Università di Roma Tor Vergata)",
    "localCoordinator": "Giulio Baù",
    "members": "C. Grassi, G.F. Gronchi",
    "startDate": "2019-08-01",
    "endDate": "2023-02-19",
    "webSite": ""
  },
     {
    "name": "Mathematical Logic: models, sets, computability",
    "identifier": "",
    "projectType": "Prin 2017",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Alessandro Berarducci",
    "localCoordinator": "Alessandro Berarducci",
    "members": "",
    "startDate": "2019-08-01",
    "endDate": "2023-02-19",
    "webSite": ""
  },
     {
    "name": "Regular and stochastic behaviour in dynamical systems",
    "identifier": "",
    "projectType": "Prin 2017",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Carlangelo Liverani (Università di Roma Tor Vergata)",
    "localCoordinator": "Claudio Bonanno",
    "members": "G. Del Magno, S. Marò",
    "startDate": "2019-08-01",
    "endDate": "2023-02-19",
    "webSite": ""
  },
     {
    "name": "Gradient flows, Optimal Transport and Metric Measure Structures",
    "identifier": "",
    "projectType": "Prin 2017",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Luigi Ambrosio (SNS, Pisa)",
    "localCoordinator": "Giuseppe Buttazzo",
    "members": "",
    "startDate": "2019-08-01",
    "endDate": "2023-02-19",
    "webSite": ""
  },
     {
    "name": "Geometric, algebraic and analytic methods in arithmetic",
    "identifier": "",
    "projectType": "Prin 2017",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Pietro Corvaja (Università di Udine)",
    "localCoordinator": "Roberto Dvornicich",
    "members": "",
    "startDate": "2019-08-01",
    "endDate": "2023-02-19",
    "webSite": ""
  },
     {
    "name": "Real and Complex Manifolds: Topology, Geometry and holomorphic dynamics",
    "identifier": "",
    "projectType": "Prin 2017",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Filippo Bracci (Università di Roma Tor Vergata)",
    "localCoordinator": "Paolo Lisca",
    "members": "Marco Abate, Giuseppe Bargagnati, Filippo Bianchi, Carlo Collari, Roberto Frigerio, Paolo Lisca, Domenico Marasco, Bruno Martelli, Alice Merz, Andrea Parma, Carlo Petronio, Andrea Tamburelli",
    "startDate": "2019-08-01",
    "endDate": "2023-02-19",
    "webSite": ""
  },
     {
    "name": "Advanced in Moduli Theory and Birational Classification",
    "identifier": "",
    "projectType": "Prin 2017",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Lucia Caporaso (Università di Roma 3)",
    "localCoordinator": "Rita Pardini",
    "members": "Marco Franciosi, Enrico Sbarra, Tamás Szamuely, Mattia Talpo",
    "startDate": "2019-08-01",
    "endDate": "2023-02-19",
    "webSite": ""
  },
     {
    "name": "Moduli and Lie Theory",
    "identifier": "",
    "projectType": "Prin 2017",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Kieran G. O'grady",
    "localCoordinator": "Mario Salvetti",
    "members": "",
    "startDate": "2019-08-01",
    "endDate": "2023-02-19",
    "webSite": ""
  },
     {
    "name": "Nonlinear evolution PDEs, fluid dynamics and transport equations: theoretical foundations and applications",
    "identifier": "Prot. 20204NT8W4_004",
    "projectType": "Prin 2020",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Stefano Bianchini (SISSA, Trieste)",
    "localCoordinator": "Luigi Carlo Berselli",
    "members": "",
    "startDate": "2022-03-22",
    "endDate": "2025-03-21",
    "webSite": ""
  },
     {
    "name": "Hamiltonian and dispersive PDEs",
    "identifier": "Prot. 2020XB3EFL",
    "projectType": "Prin 2020",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Massimiliano Berti (SISSA, Trieste)",
    "localCoordinator": "Nicola Visciglia",
    "members": "Jacopo Bellazzini, Vladimir S. Gueorguiev, Marina Ghisi, Scipio Cuccagna, Daniele Barbera, Kosuke Kita",
    "startDate": "2022-03-22",
    "endDate": "2025-03-21",
    "webSite": ""
  },
     {
    "name": "DynaMat",
    "identifier": "Prot. 2020BKWEXR",
    "projectType": "Prin 2020",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Anna Baccaglini-Frank",
    "localCoordinator": "Anna Baccaglini-Frank",
    "members": "Pietro Di Martino, Mirko Maracci",
    "startDate": null,
    "endDate": null,
    "webSite": ""
  },
     {
    "name": "Progetto Lauree Scientifiche 2019 - 2020",
    "identifier": "PLS 2019-2020",
    "projectType": "Progetto Lauree Scientifiche",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "",
    "localCoordinator": "Pietro Di Martino",
    "members": "",
    "startDate": "2020-12-31",
    "endDate": "2022-12-31",
    "webSite": ""
  },
     {
    "name": "Progetto Lauree Scientifiche - POT 2021 - 2023",
    "identifier": "PLS-POT 2021-23",
    "projectType": "Progetto Lauree Scientifiche",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "",
    "localCoordinator": "Pietro Di Martino",
    "members": "",
    "startDate": "2022-03-16",
    "endDate": "2022-10-31",
    "webSite": ""
  },
     {
    "name": "Problemi al centro",
    "identifier": "",
    "projectType": "Progetto nazionale per la scuola primaria",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "",
    "localCoordinator": "Pietro Di Martino",
    "members": "Silvia Funghi, Rosetta Zan",
    "startDate": null,
    "endDate": null,
    "webSite": ""
  },
     {
    "name": "Grant-in-Aid for Scientific Research (C): Yangians and Cohomological Hall algebras of curves",
    "identifier": "21K03197",
    "projectType": "KAKENHI JSPS",
    "funds": "Internazionale",
    "fundingEntity": "Giapponese",
    "pi": "Francesco Sala",
    "localCoordinator": "",
    "members": "",
    "startDate": "2021-04-01",
    "endDate": "2026-03-31",
    "webSite": "https://kaken.nii.ac.jp/grant/KAKENHI-PROJECT-21K03197/"
  },
     {
    "name": "Center for Advanced Research on Mathematics Education",
    "identifier": "CARME",
    "projectType": "Centro Studi",
    "funds": "Nazionale",
    "fundingEntity": "Nazionale",
    "pi": "Anna Baccaglini-Frank, Pietro Di Martino",
    "localCoordinator": "",
    "members": "",
    "startDate": null,
    "endDate": null,
    "webSite": "https://www.carme.center/"
  },
     {
    "name": "Nonlinear dispersive equations and dynamics of fluids",
    "identifier": "PRA_2022_11",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2022-2023",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "",
    "localCoordinator": "Jacopo Bellazzini",
    "members": "Elisabetta Chiodaroli, Marco Gipo Ghimenti, Carlo Romani Grisanti, Nicola Visciglia",
    "startDate": "2022-10-10",
    "endDate": "2024-12-31",
    "webSite": ""
  },
     {
    "name": "Spazi di moduli, rappresentazioni e strutture combinatorie",
    "identifier": "PRA_2022_10",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2022-2023",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "Davide Lombardo",
    "localCoordinator": "Davide Lombardo",
    "members": "Filippo Gianluca Callegaro, Michele D'adderio, Ilaria Del Corso, Filippo Disanto, Marco Franciosi, Lorenzo Furio, Giovanni Gaiffi, Andrea Maffei, Rita Pardini, Gregory James Pearlstein, Mario Salvetti, Enrico Sbarra, Viola Siconolfi, Lorenzo Stefanello ",
    "startDate": "2022-10-10",
    "endDate": "2024-12-31",
    "webSite": ""
  },
     {
    "name": "APRISE - Analysis and Probability in Science",
    "identifier": "PRA_2022_85",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2022-2023",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "Marco Romito",
    "localCoordinator": "Marco Romito",
    "members": "Andrea Agazzi, Francesco Grotto, Vladimir Georgiev, Valentino Magnani, Maria Laura Manca, Leonardo Roveri",
    "startDate": "2022-10-10",
    "endDate": "2024-12-31",
    "webSite": ""
  },
     {
    "name": "GeoDom - Geometric evolution problems and PDEs on variable domains",
    "identifier": "PRA_2022_14",
    "projectType": "Progetti di Ricerca di Ateneo (PRA) 2022-2023",
    "funds": "Nazionale",
    "fundingEntity": "Ateneo",
    "pi": "Bozhidar Velichkov",
    "localCoordinator": "Bozhidar Velichkov",
    "members": "Marina Ghisi, Massimo Gobbino, Emanuele Paolini, Alessandra Pluda, Francesca Agnese Prinari",
    "startDate": "2022-10-10",
    "endDate": "2024-12-31",
    "webSite": ""
  },
     {
    "name": "Radioscienza per BepiColombo e Juno - fase E - Attività scientifiche",
    "identifier": "",
    "projectType": "ASI-SAPIENZA UNIVERSITÀ DI ROMA n. 2015-1-Q.0",
    "funds": "Nazionale",
    "fundingEntity": "Agenzia Spaziale Italiana",
    "pi": "Luciano Iess (Università di Roma 'la Sapienza')",
    "localCoordinator": "Giacomo Tommei",
    "members": "Giacomo Lari",
    "startDate": "2022-08-02",
    "endDate": "2024-08-01",
    "webSite": ""
  },
]